@startuml mascota 

package Mascota{
class Mascota{
}
class Vehiculo
}

package Hogar{
class Casa{
    -habitacion:Habitacion
    +Decorar(Habitacion)
}
class Habitacion{}
    -cama:Cama
    +Tender(Cama)
    }
class Piano
class Cama{
    -cobija:Cobija
    +Tender(Cobija)
    }
class Cobija
}

package Prendas{
class Ropa
class Sueter{
    -gorra:Gorra
    +Usar(Gorra)
}
class Gorra
class Correa


}

package Juguete{
class Juguete
class Pelota
class Carro
class Camioneta
}

package Juegos{
class Minijuego
class Futbol
class Baquetbol
}

package Alimento{
class Alimento{
    -carne:Carne
    +Comer(Alimento)
}
class Carne
class Hueso
}

Alimento "1*" --o "1" Mascota
Mascota "1" o-- "*" Juguete
Carne  --|> Alimento
Pelota --|> Juguete
Casa "*" --o "1" Mascota
Casa "1" --o "*" Habitacion
Habitacion "1" o-- "1" Cama
Cama "1" *-- "3" Cobija
Vehiculo "*" --o "1" Mascota
Carro --|>  Vehiculo
Ropa "*" --o "1" Mascota
Sueter --|> Ropa
Gorra --|> Ropa
Hueso --|> Alimento
Mascota "1" o-- "*" Minijuego
Futbol --|> Minijuego
Pelota "1" --o "1" Futbol
Piano --> Juguete
Camioneta --> Vehiculo
Baquetbol --> Minijuego
Correa "1" --o "1"Mascota


@enduml